Solution
mate-academy/js_cat_and_dogs_years pull request #211
Opened 2022-12-14 18:41 UTC by triukhan

2022-12-14 19:29 UTC, triukhan commented
'Soloution1' is right. I am tired because of git.

2022-12-23 13:17 UTC, djtyrf312 requested changes
не всі граничні значення протестовані

2022-12-23 15:15 UTC, triukhan commented
> не всі граничні значення протестовані
добавив ще тестів на границях

2022-12-23 15:39 UTC, djtyrf312 approved these changes

2023-03-10 07:47 UTC, closed without merging